# Generated by Django 4.2.16 on 2024-11-28 17:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seat_count_first_class', models.PositiveIntegerField(default=0)),
                ('seat_count_business_class', models.PositiveIntegerField(default=0)),
                ('seat_count_economy_class', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_class', models.CharField(choices=[('first_class', 'Primera Clase'), ('business_class', 'Clase Ejecutiva'), ('economy_class', 'Clase Económica')], max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('luggage_hand', models.BooleanField(default=False)),
                ('luggage_hold', models.BooleanField(default=False)),
                ('extra_luggage', models.PositiveIntegerField(default=0)),
                ('meal_included', models.BooleanField(default=False)),
                ('extra_meal', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('is_infant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('seat_class', models.CharField(choices=[('first_class', 'Primera Clase'), ('business_class', 'Clase Ejecutiva'), ('economy_class', 'Clase Económica')], max_length=20)),
                ('is_reserved', models.BooleanField(default=False)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.airplane')),
            ],
            options={
                'unique_together': {('airplane', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('days_of_week', models.CharField(max_length=100)),
                ('available_seats', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to='flights.airplane')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='BookingPaymentCode',
            fields=[
                ('payment_code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('PENDIENTE', 'Pending'), ('PAGADO', 'Paid')], default='PENDIENTE', max_length=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(to='flights.passenger'),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.ManyToManyField(to='flights.seat'),
        ),
    ]
