# Generated by Django 4.2.16 on 2024-11-26 21:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(default='pendiente', max_length=30),
        ),
        migrations.CreateModel(
            name='ReservationPaymentCode',
            fields=[
                ('payment_code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flights.reservation')),
            ],
        ),
    ]
