# Generated by Django 5.1.3 on 2024-11-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='days_of_week',
            field=models.CharField(max_length=100),
        ),
    ]
