# Generated by Django 5.1.3 on 2024-11-28 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingScales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('luggage_hand', models.BooleanField(default=False)),
                ('luggage_hold', models.BooleanField(default=False)),
                ('extra_luggage', models.PositiveIntegerField(default=0)),
                ('meal_included', models.BooleanField(default=False)),
                ('extra_meal', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSeatInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.seat')),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_stopover', models.BooleanField(default=False)),
                ('stopover_order', models.PositiveIntegerField(blank=True, null=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.passenger')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.bookingscales')),
                ('flightSeat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightseatinstance')),
            ],
        ),
    ]
