# Generated by Django 5.1.3 on 2024-11-26 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_airplane_passenger_flight_available_seats_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='airplane',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.airplane'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
