# Generated by Django 5.1.3 on 2024-11-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airport')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='flights.flight')),
            ],
        ),
    ]
